"""empty message

Revision ID: 039c2968fcbb
Revises: 0763d677d453
Create Date: 2025-06-05 16:14:07.383863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '039c2968fcbb'
down_revision = '0763d677d453'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('nombre', sa.String(length=100), nullable=False),
                    sa.Column('email', sa.String(length=120), nullable=False),
                    sa.Column('contraseña', sa.String(
                        length=120), nullable=False),
                    sa.Column('tipo_usuario', sa.Enum('paciente', 'medico',
                                                      name='tipousuario'), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email')
                    )
    op.create_table('medicos',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('especialidad', sa.String(
                        length=100), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('pacientes',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('direccion', sa.String(
                        length=255), nullable=False),
                    sa.Column('telefono', sa.String(
                        length=20), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('analisis',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('tipo_analisis', sa.String(
                        length=100), nullable=False),
                    sa.Column('resultado', sa.String(), nullable=False),
                    sa.Column('fecha', sa.DateTime(), nullable=False),
                    sa.Column('paciente_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['paciente_id'], ['pacientes.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('citas',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('fecha_hora', sa.DateTime(), nullable=False),
                    sa.Column('estado', sa.String(length=20), nullable=False),
                    sa.Column('tipo', sa.String(length=20), nullable=False),
                    sa.Column('paciente_id', sa.Integer(), nullable=False),
                    sa.Column('medico_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['medico_id'], ['medicos.id'], ),
                    sa.ForeignKeyConstraint(
                        ['paciente_id'], ['pacientes.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('farmacos_alergenos',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('nombre_farmaco', sa.String(
                        length=100), nullable=False),
                    sa.Column('reaccion', sa.Text(), nullable=False),
                    sa.Column('paciente_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['paciente_id'], ['pacientes.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('historiales',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('diagnostico', sa.Text(), nullable=False),
                    sa.Column('tratamiento', sa.Text(), nullable=False),
                    sa.Column('fecha', sa.DateTime(), nullable=False),
                    sa.Column('paciente_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['paciente_id'], ['pacientes.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
                    sa.Column('id', sa.INTEGER(),
                              autoincrement=True, nullable=False),
                    sa.Column('email', sa.VARCHAR(length=120),
                              autoincrement=False, nullable=False),
                    sa.Column('password', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('is_active', sa.BOOLEAN(),
                              autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint('id', name='user_pkey'),
                    sa.UniqueConstraint('email', name='user_email_key')
                    )
    op.drop_table('historiales')
    op.drop_table('farmacos_alergenos')
    op.drop_table('citas')
    op.drop_table('analisis')
    op.drop_table('pacientes')
    op.drop_table('medicos')
    op.drop_table('users')
    # ### end Alembic commands ###
