"""empty message

Revision ID: 3bc6cbc15149
Revises: 039c2968fcbb
Create Date: 2025-06-06 06:58:34.211779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bc6cbc15149'
down_revision = '039c2968fcbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('password', sa.String(length=120), nullable=False))
        batch_op.drop_constraint('users_correo_key', type_='unique')
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.drop_column('correo')
        batch_op.drop_column('contraseña')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contraseña', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('correo', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('users_correo_key', ['correo'])
        batch_op.drop_column('password')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
