"""empty message

Revision ID: e8e3bbd6e473
Revises: 46bade81c849
Create Date: 2025-06-06 07:35:00.966334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8e3bbd6e473'
down_revision = '46bade81c849'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pacientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_nacimiento', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('genero', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('tipo_sangre', sa.String(length=5), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pacientes', schema=None) as batch_op:
        batch_op.drop_column('tipo_sangre')
        batch_op.drop_column('genero')
        batch_op.drop_column('fecha_nacimiento')

    # ### end Alembic commands ###
